version: 0.2
env:
  shell: "/bin/sh"
  variables:
    IMAGE_TAG: frontend
  parameter-store:
    CLUSTER_NAME: cluster-name
    ECR_REGISTRY_URI: ecr-registry-uri
    AWS_DEFAULT_REGION: default-region-aws
    ACCOUNT_ID: account-id

phases:
  install:
    runtime-versions:
      php: 8.2

  pre_build:
    commands:
      
      - export KUBECONFIG=$HOME/.kube/config
   
      
  build:
    commands:
      - echo "Setting Environment Variables related to AWS CLI for Kube Config Setup"
      - CREDENTIALS=$(aws sts assume-role --role-arn arn:aws:iam::$ACCOUNT_ID:role/service-role/Vaccination-CodeBuildServiceRole --role-session-name eks-codebuild --region $AWS_DEFAULT_REGION)
      - export AWS_ACCESS_KEY_ID="$(echo ${CREDENTIALS} | jq -r '.Credentials.AccessKeyId')"
      - export AWS_SECRET_ACCESS_KEY="$(echo ${CREDENTIALS} | jq -r '.Credentials.SecretAccessKey')"
      - export AWS_SESSION_TOKEN="$(echo ${CREDENTIALS} | jq -r '.Credentials.SessionToken')"
      - export AWS_EXPIRATION=$(echo ${CREDENTIALS} | jq -r '.Credentials.Expiration')
      - echo "Update Kube Config"
      - aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_DEFAULT_REGION
      
  post_build:
    commands:
      - echo "Apply changes to kube manifests"  
      - kubectl get pods -A
      - kubectl apply -f k8s-manifests/frontend-autoscaling.yaml
      - kubectl apply -f k8s-manifests/frontend-dev-loadbalancer.yaml
      - envsubst < k8s-manifests/frontend-dev.yaml | kubectl apply -f -
      - envsubst < k8s-manifests/frontend-dev.yaml | kubectl rollout restart -f -
    
privilegedMode: true
